// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hA-FvE0sQ6b1M-VPSFYVPkmdMYIUuaM',
    appId: '1:417146340408:web:4d4496c28090d8323852cd',
    messagingSenderId: '417146340408',
    projectId: 'fir-flutter-codelab-dd42',
    authDomain: 'fir-flutter-codelab-dd42.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-dd42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXnbYFeDfQXOTEIySJN_AQ5bpXaW-PRI0',
    appId: '1:417146340408:android:e2e968cb93f33e603852cd',
    messagingSenderId: '417146340408',
    projectId: 'fir-flutter-codelab-dd42',
    storageBucket: 'fir-flutter-codelab-dd42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-AiJP0S9wbSzFOBq5-S0nommlgUMQDg',
    appId: '1:417146340408:ios:5082a605404e443d3852cd',
    messagingSenderId: '417146340408',
    projectId: 'fir-flutter-codelab-dd42',
    storageBucket: 'fir-flutter-codelab-dd42.appspot.com',
    iosClientId: '417146340408-uq1sij2pfn1hnuom5l3mogp8ndk2s7t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-AiJP0S9wbSzFOBq5-S0nommlgUMQDg',
    appId: '1:417146340408:ios:77a9e29a5c2621333852cd',
    messagingSenderId: '417146340408',
    projectId: 'fir-flutter-codelab-dd42',
    storageBucket: 'fir-flutter-codelab-dd42.appspot.com',
    iosClientId: '417146340408-30kb2jqi2nmc41upadi4ba4hfn7g33it.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
